[package]
name = "prusti-contracts-test"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2021"

[dependencies]
prusti-contracts = { path = "../prusti-contracts" }

[workspace]
